ldap:
  url: ldap://ds0.socialhistoryservices.org/dc=socialhistoryservices,dc=org
  manager:
    dn: cn=admin,dc=socialhistoryservices,dc=org
    password: G3tL0st
  search:
    base: ou=users
    filter: cn={0}