spring:
  datasource:
    invoer:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/invoer?useSSL=false&serverTimezone=UTC
      jdbcUrl: jdbc:mysql://localhost:3306/invoer?useSSL=false&serverTimezone=UTC
      username: root
      password: rootroot

      initialize: false
      continueOnError: false
      separator: ;
      maxActive: 100
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      validationQuery: SELECT 1
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      maxWait: 10000
      jmxEnabled: true
      useServerPrepStmts: false
      rewriteBatchedStatements: true

    reference:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reference?useSSL=false&serverTimezone=UTC
      jdbcUrl: jdbc:mysql://localhost:3306/reference?useSSL=false&serverTimezone=UTC
      username: root
      password: rootroot

      initialize: false
      continueOnError: false
      separator: ;
      maxActive: 100
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      validationQuery: SELECT 1
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      maxWait: 10000
      jmxEnabled: true
      useServerPrepStmts: false
      rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.iish.hsn.invoer.util.HsnPhysicalNamingStrategy

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jdbc:
      batch_size: 30
      batch_versioned_data: true
  order_inserts: true
  order_updates: true