application:
  version: "5.6.5"
  date: "3 maart 2023"

storage:
  path: "/data/hsn/"

spring:
  web:
    locale: nl_NL

  mvc:
    format:
      date: dd-MM-yyyy

  servlet:
    multipart:
      max-file-size: '50MB'
      max-request-size: '50MB'

  http:
    multipart:
      enabled: true
      max-file-size: '50MB'
      max-request-size: '50MB'

  session:
    store-type: 'jdbc'
