application:
  version: "5.5.0"
  date: "5 oktober 2020"

storage:
  path: "/data/hsn/"

spring:
  mvc:
    locale: nl_NL
    date-format: dd-MM-yyyy

  servlet:
    multipart:
      max-file-size: '50MB'
      max-request-size: '50MB'

  http:
    multipart:
      enabled: true
      max-file-size: '50MB'
      max-request-size: '50MB'
