spring:
  datasource:
    invoer:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/invoer-2
      username: root
      password:

      initialize: false
      continueOnError: false
      separator: ;
      maxActive: 100
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      validationQuery: SELECT 1
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      maxWait: 10000
      jmxEnabled: true

    reference:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reference
      username: root
      password:

      initialize: false
      continueOnError: false
      separator: ;
      maxActive: 100
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      validationQuery: SELECT 1
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 60000
      maxWait: 10000
      jmxEnabled: true

  jpa:
    hibernate:
      ddl-auto: none
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect